export const AGENT_BROWSER_NONO_FALLBACK_EXTENSION_FILE = 'agent-browser-nono-fallback.ts';

/** Emit the sandbox-only environment bridge agent-browser needs when launched as a pi subprocess. */
export function emitAgentBrowserNonoFallbackExtension(): string {
  return `// generated by cradle for sandboxed agent-browser processes — do not edit
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

export default function configureAgentBrowserNonoEnvironment(_pi: ExtensionAPI): void {
  if (process.platform === 'darwin') {
    const agentBrowserArgs = (process.env.AGENT_BROWSER_ARGS ?? '')
      .split(/[,\\n]/)
      .map(value => value.trim())
      .filter(value => value !== '' && value !== '--no-sandbox');
    process.env.AGENT_BROWSER_ARGS = [...agentBrowserArgs, '--no-sandbox'].join(',');
  }

  const nonoProxy = process.env.HTTPS_PROXY ?? process.env.HTTP_PROXY;
  if (process.env.AGENT_BROWSER_PROXY === undefined && nonoProxy !== undefined) {
    process.env.AGENT_BROWSER_PROXY = nonoProxy;
  }
}
`;
}
