import { rewriteLocalhostBaseUrl } from '../../sbx/compose.js';

/** Options for `emitProvidersExtension` — see `commands/start.ts`'s `emitExtensionFiles`, the single call site. */
export interface ProvidersEmitOptions {
  /**
   * Rewrite `localhost`/`127.0.0.1` provider baseUrls to the sbx host gateway
   * (see `sbx/compose.ts`'s `rewriteLocalhostBaseUrl`): guest loopback is the
   * microVM itself, so a host-bound local-model endpoint is unreachable under
   * its own name inside the sbx backend. Off (byte-identical output) for nono
   * and unsandboxed runs.
   */
  readonly rewriteLocalhostBaseUrls?: boolean;
}

export function emitProvidersExtension(providersJson: string, options: ProvidersEmitOptions = {}): string {
  const json = options.rewriteLocalhostBaseUrls === true ? rewriteProviderBaseUrls(providersJson) : providersJson;
  return `// generated by cradle from the agent folder's models.json — do not edit
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

const providers = ${json} as const;

export default function (pi: ExtensionAPI): void {
  for (const [name, config] of Object.entries(providers)) {
    pi.registerProvider(name, config as never);
  }
}
`;
}

/**
 * `providersJson` is `folder.ts`'s validated `providers` serialization
 * (2-space indent), so re-serializing with the same indent round-trips
 * unchanged apart from the rewritten hosts.
 */
function rewriteProviderBaseUrls(providersJson: string): string {
  const providers = JSON.parse(providersJson) as { readonly [key: string]: unknown };
  for (const provider of Object.values(providers)) {
    if (provider === null || typeof provider !== 'object') continue;
    const record = provider as { [key: string]: unknown };
    if (typeof record['baseUrl'] === 'string') record['baseUrl'] = rewriteLocalhostBaseUrl(record['baseUrl']);
  }
  return JSON.stringify(providers, null, 2);
}
