export function emitProvidersExtension(providersJson: string): string {
  return `// generated by cradle from the agent folder's models.json — do not edit
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

const providers = ${providersJson} as const;

export default function (pi: ExtensionAPI): void {
  for (const [name, config] of Object.entries(providers)) {
    pi.registerProvider(name, config as never);
  }
}
`;
}
